### ISSUE TITLE
No ta el generador

### ISSUE THREAD

**Issue by zeusito** [flkt-crnpio/pitaya#1]
Me gustan las animaciones, cuando sale la versión 1? 👍

**Comment by flkt-crnpio** [comment]
pa' mi cumpleaños! (28 mayo)

**Comment by zeusito** [comment]
ya lo quierooo!, y el demo?

**Comment by flkt-crnpio** [comment]
ooooohhhhh tsss perese! al menos andas acá en guanatos o qué?

**Comment by flkt-crnpio** [comment]
ahhh!!! no salió, taba cruda @zeusito sigo trabajando, por favor, espere un momento... =D

**Comment by rdosantillan** [comment]
¿Ya quedó? No veo la documentación....

**Comment by flkt-crnpio** [comment]
ash.. les comprarto el trello mejor n.n

**Comment by rdosantillan** [comment]
Jojojo! Te estoy peleando :p

**Comment by flkt-crnpio** [comment]
hahahaha.. par de pelioneros!

**Comment by flkt-crnpio** [comment]
https://flkt.mx/pitaya/ pos yo se que ya ni andan aca @rdosantillan @zeusito pero ahi esta desde hace aaaaños... hahahaha :} besho

**Comment by zeusito** [comment]
hey porque cierras nuestro thread? jajaja.... No había visto tu sitio, esta genial, cuando la versión 2?

**Comment by flkt-crnpio** [comment]
ah mira, si esta el @zeusito ! 
pues asi como version 2 no creo que salga, la verdad tiene problemas con el manejo de los colores y he estado resolviendolo pero en otra librería que ahora se llamará 'mol' ahi luego te voy mandando mas info :}

**Comment by rdosantillan** [comment]
Con que cerrando issues sin resolver @flkt-crnpio !! 😑 
Srrrr!! @zeusito Tas vivo!!

**Comment by flkt-crnpio** [comment]
na mas corre el script de sass en la terminal vago, en el readme dice ... oiga pos este pelionero @rdosantillan jejeje . hey! siglos sin verlos a los dos. amos por la chelas o que @zeusito @rdosantillan

**Comment by zeusito** [comment]
siiii, chelasss, ustedes dicen jeje,. @rdosantillan tanto tiempo sr, y si, seguimos vivos jajaaja.. @flkt-crnpio queremos un framework nuevo :-)
