### ISSUE TITLE
Tabs break when you press 'tab'

### ISSUE THREAD

**Issue by goremukin** [flkt-crnpio/pitaya#2]
Thank you for the work done, it is really very beautiful! I noticed only a small problem when pressing the 'tab'key. Prompt how it is possible to correct it?

![image](https://user-images.githubusercontent.com/25577658/45168947-29c29a00-b205-11e8-9121-bb6a6936e051.png)
![image](https://user-images.githubusercontent.com/25577658/45168970-334c0200-b205-11e8-9802-53d94d30d79f.png)
(In the screenshots the consequences of tabulation)

**Comment by flkt-crnpio** [comment]
woooo so weird! thanks for the screenshot. i'm sorry that i read this until now.. hehe. i'm going to try to fix that, thanks @goremukin

**Comment by flkt-crnpio** [comment]
ahhh. well is fixed, if you need the long story, @goremukin , please write me :}
